# Ambiente
testnet: true                # true para Testnet, false para Produção
mode: trade                  # trade | backtest
log_level: INFO               # DEBUG | INFO | WARNING | ERROR
timeframe: "1m"               # Timeframe padrão (pode ser alterado via dashboard)

# Pares operados
symbols:
  - BTCUSDT
  - ETHUSDT

# Estratégias por par
strategies:
  BTCUSDT:
    - ema_cross
    - rsi
  ETHUSDT:
    - ema_cross

# Parâmetros globais das estratégias
ema_cross:
  fast_period: 9
  slow_period: 21

rsi:
  period: 14
  overbought: 70
  oversold: 30

# Gestão de risco
risk:
  capital_per_trade_pct: 5     # % do saldo USDT por trade
  stop_loss_pct: 1.0           # % perda máxima por trade
  take_profit_pct: 2.0         # % ganho alvo por trade
  max_daily_loss_pct: 5.0      # % perda máxima diária
  max_trades_per_day: 10       # máximo de trades/dia

# IA (otimização automática)
ia:
  enabled: false
  retrain_every: 1             # dias

# Backtest
backtest:
  source: csv
  candles_per_second: 50
  warmup: 200
  quote_per_trade_usdt: 100
  auto_save_csv: true
  auto_download_if_missing: true
  api:
    last_days: 15
  csv:
    folder: data/backtest
    pattern: "{symbol}_{interval}.csv"

